#!/usr/bin/env bash
#To Configure Nginx server so that /redirect_me is redirecting to another page.

apt-get update
apt-get install -y nginx
sudo bash -c 'cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location /redirect_me {
        return 301 https://example.com/new-page;
    }
}" > /etc/nginx/sites-available/default
EOF'
service nginx restart
