#!/usr/bin/env bash

# Configures a brand new Ubuntu machine to the requirements:
# Configure Nginx so that its HTTP response contains
# a custom header (on web-01 and web-02).
# The name of the custom HTTP header must be X-Served-By.
# The value of the custom HTTP header must be the
# hostname of the server Nginx is running on.
# Customizing a 404-error_page

# Updating Packages before performing installations
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performs a "moved permanently redirection" (301)
new_string="server_name _;\n\trewrite ^\/redirect_me :https://whois.whoisxmlapi.com/;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-available/default

# Creates a 404 Custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-available/default

# Creates an HTTP response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

# Testing configuration syntax errors
sudo nginx -t

sudo service nginx restart
