#!/usr/bin/env bash
# The script displays "Best School" 10 times using a while loop.

# Initializes a counter
counter=1

while [ $counter -le 10 ]
do
    echo "Best School"
    
    # Increment the counter
    ((counter++))
done
