#!/usr/bin/env bash
# The script displays "Best School" 10 times,
# but for the 9th iteration, displays Best School and then Hi on a new line.

# Initializes a counter
counter=1

while [ $counter -le 10 ]
do
    if [ $counter -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((counter++))
done
