#!/usr/bin/env bash
# The script displays bad luck for the 4th loop iteration,
# Displays good luck for the 8th loop iteration
# Displays Best School for the other iterations.

# Initializes a counter
counter=1

while [ $counter -le 10 ]
do
    if [ $counter -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((counter++))
done
