#!/usr/bin/env bash
# The script displays the contents of the current directory.
# In list format.
# Where only the part of the name after the first dash is displayed.

list=$(ls)

# Using a for loop to iterate over files in the current directory
for i in $list; do
    if [[ ! "$i" == .* ]]; then
        if [[ "$i" == *-* ]]; then
            name_after_dash="${i#*-}" 
            echo "$name_after_dash"
        else
            echo "$i"
        fi
    fi
done
