#!/usr/bin/env bash

chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
sed -i '/listen 8080 default_server/d' /etc/nginx/sites-enabled/default
echo -e "listen 8080;\n\tlisten [::]:8080;" >> /etc/nginx/sites-enabled/default
pkill apache2
su nginx -s /bin/bash -c 'service nginx restart'
