#!/usr/bin/env bash

# Script that uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu.
# Only use ssh single-character flags
# You cannot use -l
# You do not need to handle the case of a private key protected by a passphrase

ssh -i ~/.ssh/school ubuntu@100.24.206.10
