#!/usr/bin/env bash

#The script that creates an RSA key pair.
#Name of the created private key must be school
#Number of bits in the created key to be created 4096
#The created key must be protected by the passphrase betty

# Defines variables
private_key="school"
key_bits="4096"
passphrase="betty"

# Generates RSA key pair
ssh-keygen -t rsa -b "$key_bits" -f ~/.ssh/"$private_key" -N "$passphrase"

echo "RSA key pair generated successfully."
