#!/usr/bin/env bash

#The script that creates an RSA key pair.
#Name of the created private key must be school
#Number of bits in the created key to be created 4096
#The created key must be protected by the passphrase betty

read -s -p "Enter passphrase for the private key: " passphrase
echo

ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -N "$passphrase"

echo "RSA key pair created successfully."
